/*
 * This source file was generated by the Gradle 'init' task
 */
package org.ecommerce;

public class EcommerceApplication {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new EcommerceApplication().getGreeting());
    }
}
