/*
 * This source file was generated by the Gradle 'init' task
 */
package org.ecommerce;

import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class EcommerceApplicationTest {
}